#!/bin/bash

which csv >& /dev/null
if [[ $? -ne 0 ]]
then
  echo "Add this script's directory to the PATH"
else
  DIR=`dirname $(which csv)`
  if [[ $# < 2 ]]
  then
    awk -f $DIR"/csv.awk" $1
  else 
    awk -f $DIR"/csv.awk" -v "regex=$1" $2
  fi
fi
